### PR TITLE
Add design_gallery files for AM67/AM68/AM69 under new directory structure

### PR DESCRIPTION
**Pull request by aniket-l**

### CODE REVIEW

**Review by cshilwant — CHANGES_REQUESTED** [review]
Hi Aniket,

The directory structure that would avoid redundancy is something like,
design_gallery
|-- images
|-- web_support
|-- index-platform1.html
|-- index-platform2.html

The PR you created still would add redundant copies of web_support/ directory under every platform folder. 
So, I would appreciate if you can update the PR to follow the directory structures as I mentioned above or hold on as anyways I'm planning to do the changes (maybe by 18/03).

**Comment by aniket-l** [comment]
@cshilwant Sure, makes sense... I can update the PR with this change... Wanted to get this in to add AM67 support soon
Can I also merge the existing 2 platform folders then? Just copy over the right index.html files with the new platform names right?

**Comment by cshilwant** [comment]
@aniket-l 

> Sure, makes sense... I can update the PR with this change

Cool. 

> Can I also merge the existing 2 platform folders then? Just copy over the right index.html files with the new platform names right?

Yes, that's all. 
index-platform.html can be convention I can think of.

**Comment by aniket-l** [comment]
@cshilwant Done!

**Review by cshilwant — APPROVED** [review]
LGTM!

**Pull request merged**
